name: ci

on: push 

jobs:
  test1:
    runs-on: ubuntu-latest
    container: mtmiller/octave
    steps:
      - uses: actions/checkout@v3
      - run: echo "Running 1.2.0"
      - run: octave --eval "version"

  test2:
    runs-on: ubuntu-latest
    container: matpower/octave
    steps:
      - uses: actions/checkout@v3
      - run: echo "Running 1.2.0"
      - run: octave --eval "version"

  test3:
    runs-on: ubuntu-latest
    container: matpower/octave
    steps:
      - uses: actions/checkout@v3
      - run: |
          git clone https://github.com/ONSAS/ONSAS.m.git
          cd ONSAS.m/test
          octave --eval "runTestProblems_local"

  test4:
    runs-on: ubuntu-latest
    container: matpower/octave
    steps:
      - uses: actions/checkout@v3
      - run: |
          git clone https://github.com/ONSAS/ONSAS.m.git
          cd ONSAS.m/test
          octave --eval "runTestProblems_local"
  test5:
    runs-on: ubuntu-latest
    container: gnuoctave/octave:latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git clone https://github.com/ONSAS/ONSAS.m.git
          cd ONSAS.m/test
          octave --eval "runTestProblems_local"
          octave --eval "version"



