name: ci

on: push 

jobs:
  test1:
    runs-on: ubuntu-latest
    container: mtmiller/octave
    steps:
      - uses: actions/checkout@v3
      - run: echo "Running 1.2.0"
      - run: octave --eval "hello"

  test2:
    runs-on: ubuntu-latest
    container: matpower/octave
    steps:
      - uses: actions/checkout@v3
      - run: echo "Running 1.2.0"
      - run: octave --eval "hello"
